<h4>To Do:</h4>
1. Check for correlation/relationship between EMT and ATF4 signatures

  
```{r defineFunctions, include=FALSE}
foldChange <- function(eset, groups, genes){
  apply(exprs(eset)[genes, groups==0], 1, mean) - 
    apply(exprs(eset)[genes, groups==1], 1, mean)
}

medianFilter <- function(eset){
  md <- median(exprs(eset))
  passFilter <- logical(featureNumber(eset))
  for(i in 1:featureNumber(eset)){
    passFilter[i] <- sum(exprs(eset)[i, ] > md) > 0
  }
  
  eset <- eset[passFilter, ]
  return(eset)
  
}

saveGeneList <- function(analysis, filename=paste(Sys.Date(), "Temp", analysis$name, ".txt", sep="")){
  
  write.table(analysis$geneSymbols, file=filename, quote=FALSE,row.names=FALSE, col.names=FALSE)

}

saveRankedList <- function(fit, varColInd, filename = "tempRankedList"){
  filename = paste(paste(Sys.Date(), colnames(fit$t)[varColInd], filename, sep="_"), "rnk", sep=".")
  print(filename)
  temp <- data.frame(geneSymbols = fit$genes$Symbol, ts = fit$t[, varColInd])
  write.table(temp, file=filename, row.names=FALSE, quote=FALSE, col.names=TRUE, sep="\t", eol="\n")
  
  
}

saveGeneSet <- function(fit, inds, filename = "tempGeneSet", geneSetName="GeneSet", description=""){
  filename = paste(paste(Sys.Date(), filename, sep="_"), "gmx", sep=".")
  print(filename)
  temp <- data.frame(geneSymbols=c(geneSetName, description, fit$genes$Symbol[inds]))
  write.table(temp, file=filename, row.names=FALSE, quote=FALSE, col.names=FALSE)
  
}


```

```{r setup, eval=TRUE, echo=TRUE, include=FALSE, results='hide'}

setwd("/protected/projects/pulmarray/Allegro/COPD_Cancer/experiments/2015-05-28_ATF4_EMT_Relationship/")
source("/protected/projects/pulmarray/Allegro/COPD_Cancer/scripts/AllegroSetup.R")
source("../2015-05-03_CBM_ATS_2015/plotGSEA.R")
# fix the one patient with wonky data
# eventually this should just be saved in the RDS file
holdEset <- eset
holdEset$FEV1Pc[holdEset$FEV1Pc==89.2] <- 0.892

emt_genes <- read.csv("/protected/projects/pulmarray/Allegro/COPD_Cancer/geneSubsets/emt_gene_symbols_byers_2013.csv", header=FALSE)
temp <- as.factor(unique(as.character(emt_genes$V1)))
emt_genes <- data.frame("EMT_Genes" = temp)

GOLD_colors = c("0" = "gray100", "1" = "gray75", "2" = "gray50", "3" = "gray25", "4" = "black")

# load ATF4 BEASB2 gene perturbation data for analysis
atf4_data <- readRDS("/protected/projects/pulmarray/Allegro/ATF4/ATF4data_2015MAR17_ExpressionSet.rds")

lam_sign <- read.delim("/protected/projects/pulmarray/Allegro/COPD_Cancer/geneSubsets/katie98genesEntrez.txt")
lam_sign[, 3] <- paste(lam_sign[, 2], "_at", sep="")

#atf4_targets <- read.delim("ATF4_Targets_Enrichr_TRANSFACJASPAR_270Genes.txt", sep=",", as.is=TRUE, header=FALSE)
#atf4_targets <- as.character(atf4_targets)

#a4LEup <- read.delim("ATF4_targets_cluster1_270Genes_LeadingEdge_Up.csv", header=FALSE)
#a4LEup <- as.character(a4LEup$V1)

#a4LEdn <- read.delim("ATF4_targets_cluster2_270Genes_LeadingEdge_Down.csv", header=FALSE)
#a4LEdn <- as.character(a4LEdn$V1)
library(znorm)
library(diptest)
library(GSVA)


```

```{r cleanup}

# Remaining question - should we keep or remove the COPD GOLD Status 1 patients? i.e. mild disease
# What about patients using or their charts indicating they have used corticosteroids?
esetClean <- holdEset
esetClean <- cleanNAForAnalysis(esetClean, "COPD2_R7")
esetClean <- cleanNAForAnalysis(esetClean, "RATIOc")
esetClean <- cleanNAForAnalysis(esetClean, "PYc")
esetClean <- cleanNAForAnalysis(esetClean, "RIN")
esetClean <- removeFactorLevel(esetClean, "COPD2_R7", "DK")
esetClean <- removeFactorLevel(esetClean, "FinalCaDXc", "DK")
esetClean <- removeFactorLevel(esetClean, "COPD2_R7", "DK")
esetClean <- removeFactorLevel(esetClean, "GENDERc", "DK")

esetClean <- calcIndicator(esetClean, "FinalCaDXc", "COPD2_R7")
esetClean$smkindic <- as.numeric(as.character(esetClean$indicator))
esetClean$smkindic[esetClean$SMKc==2] <- esetClean$smkindic[esetClean$SMKc==2] + 4
esetClean$smkindic <- as.factor(esetClean$smkindic)

# Define the GOLD Stage appropriate for all patients
esetClean$GOLD <- factor(x=rep(0, sampleNumber(esetClean)), levels=c("0","1","2","3","4"))
# GOLD Stage 1 Ratio < 0.7, FEV1 >= 8
esetClean$GOLD[esetClean$RATIOc < 0.7 & esetClean$FEV1Pc >= 0.8] <- 1
# GOLD Stage 2 Ratio < 0.7, 50 <= FEV1 < 80
esetClean$GOLD[esetClean$RATIOc < 0.7 & esetClean$FEV1Pc < 0.8] <- 2
# GOLD Stage 3 Ratio < 0.7, 30 <= FEV1 <= 50
esetClean$GOLD[esetClean$RATIOc < 0.7 & esetClean$FEV1Pc < 0.5] <- 3
# GOLD Stage 4 Ratio < 0.7, FEV1 < 30%
esetClean$GOLD[esetClean$RATIOc < 0.7 & esetClean$FEV1Pc < 0.3] <- 4

esetCleanFormers <- removeFactorLevel(esetClean, "SMKc", "1")
esetCleanCurrents <- removeFactorLevel(esetClean, "SMKc", "2")
# Generate a super clean dataset devoid of all patients with other pulmonary diseases
esetSuperClean <- esetClean
esetSuperClean <- removeFactorLevel(esetSuperClean, "AllegroPNAc", "1")
esetSuperClean <- removeFactorLevel(esetSuperClean, "AllegroTBc", "1")
esetSuperClean <- removeFactorLevel(esetSuperClean, "AllegroSarcoidc", "1")
esetSuperClean <- removeFactorLevel(esetSuperClean, "AllegroIPFc", "1")
esetSuperClean <- removeFactorLevel(esetSuperClean, "AllegroIPFc", "DK")
esetSuperClean <- removeFactorLevel(esetSuperClean, "AllegroAtelectasisc", "1")
esetSuperClean <- removeFactorLevel(esetSuperClean, "AllegroAtelectasisc", "DK")
esetSuperClean <- removeFactorLevel(esetSuperClean, "AllegroAsthmac", "DK")
esetSuperClean <- removeFactorLevel(esetSuperClean, "AllegroAsthmac", "1")

# clean up ATF4 data
varLabels(atf4_data) <- "SampleID"
atf4_data$SampleID[grep("ATF4", atf4_data$SampleID)] <- "ATF4"
atf4_data$SampleID[grep("Ctrl", atf4_data$SampleID)] <- "Control"
atf4_data$SampleID <- as.factor(atf4_data$SampleID)

atf4_colors <- c("ATF4" = "red", "Control" = "black")


```


```{r interactionModels, eval=TRUE, echo=TRUE, results='hide'}

# Katie uses age, sex, smoking, and pack years
# She also attempts to account for corticosteroids by removing them, repeating
# the analysis and checking for enrichment in the overlapping genes

eset <- medianFilter(esetCleanFormers)
fdrVals <- c(0.05, 0.1, 0.2)
intrxA <- list()
intrxB <- list()
intrxC <- list()
intrxGenes <- list()

for(i in 1:length(fdrVals)){
  
  intrxA[[i]] <- lmFitWrapper(eset, c("COPD2_R7", "FinalCaDXc", "AGEcalc",
                                     "GENDERc", "PYc", "RIN",
                                    "COPD2_R7*FinalCaDXc"),
                             name="COPD*Cancer Signal",
                             adjust.method="fdr", p.value=fdrVals[i],
                             varOfInterest=7)
                             
  intrxB[[i]] <- lmFitWrapper(eset, c("FEV1Pc", "FinalCaDXc", "AGEcalc",
                                     "GENDERc", "PYc", "RIN",
                                     "FEV1Pc*FinalCaDXc"),
                             name="FEV1%*Cancer Signal",
                             adjust.method="fdr", p.value=fdrVals[i],
                             varOfInterest=7)

	intrxC[[i]] <- lmFitWrapper(eset, c("RATIOc", "FinalCaDXc", "AGEcalc",
                                     "GENDERc", "PYc", "RIN",
                                     "RATIOc*FinalCaDXc"),
                             name="RATIO*Cancer Signal",
                             adjust.method="fdr", p.value=fdrVals[i],
                             varOfInterest=7)

	overlappingGenes <- intrxA[[i]]$geneSymbols[intrxA[[i]]$geneSymbols %in% intrxB[[i]]$geneSymbols]
	intrxGenes[[i]] <- overlappingGenes[overlappingGenes %in% intrxC[[i]]$geneSymbols]

	length(intrxA[[i]]$geneSymbols)
	length(intrxB[[i]]$geneSymbols)
	length(intrxC[[i]]$geneSymbols)
	length(intrxGenes[[i]])
	
}


# generate ATF4 model(s)
atf4Model <- lmFitWrapper(atf4_data, c("SampleID"),
                          name="ATF4 Perturbation Data", adjust.method="none",
                          p.value=0.01, varOfInterest=1)

clabels <- cbind(atf4_colors[atf4_data$SampleID])
heatmap3(exprs(atf4_data)[atf4Model$inds, ], col = bluered,
         hclustfun=function(d) hclust(d, method="ward.D"),
         col.clustering = atf4_data$SampleID, ColSideColors = clabels,
         main = "ATF4 Genes",
         labCol="")

```


```{r atf4_emt_gsva_Clean}
genesets <- list(atf4=atf4Model$geneSymbols, emt=as.character(emt_genes$EMT_Genes))
forGenes <- lmFitWrapper(esetClean, c("RIN"),1, "fdr", 0.05, "For Genes")
esetGS <- esetClean
gnsb <- forGenes$fit$genes$Symbol[which(!is.na(forGenes$fit$genes$Symbol))]
inds <- match(gnsb, forGenes$fit$genes$Symbol)

esetGS <- esetGS[inds, ]
rownames(esetGS) <- gnsb

require(GSVA)

# in place of genes this creates a row per gene set with a score per sample
gsvaResults <- gsva(esetGS, genesets)

x# Check for differences in atf4 and emt scores between COPD status groups
t.test(exprs(gsvaResults$es.ob)[1, gsvaResults$es.obs$COPD2_R7==0], exprs(gsvaResults$es.ob)[1, gsvaResults$es.obs$COPD2_R7==1])
t.test(exprs(gsvaResults$es.ob)[2, gsvaResults$es.obs$COPD2_R7==0], exprs(gsvaResults$es.ob)[2, gsvaResults$es.obs$COPD2_R7==1])

# Check for differences in atf4 and emt scores between Cancer status groups
t.test(exprs(gsvaResults$es.ob)[1, gsvaResults$es.obs$FinalCaDXc==0], exprs(gsvaResults$es.ob)[1, gsvaResults$es.obs$FinalCaDXc==1])
t.test(exprs(gsvaResults$es.ob)[2, gsvaResults$es.obs$FinalCaDXc==0], exprs(gsvaResults$es.ob)[2, gsvaResults$es.obs$FinalCaDXc==1])

# Check for differences in atf4 and emt scores between COPD+Cancer and COPD
t.test(exprs(gsvaResults$es.ob)[1, gsvaResults$es.obs$indicator==3], exprs(gsvaResults$es.ob)[1, gsvaResults$es.obs$indicator==4])
t.test(exprs(gsvaResults$es.ob)[2, gsvaResults$es.obs$indicator==3], exprs(gsvaResults$es.ob)[2, gsvaResults$es.obs$indicator==4])

cor.test(exprs(gsvaResults$es.ob)[1, 1:sampleNumber(gsvaResults$es.ob)], exprs(gsvaResults$es.ob)[2, 1:sampleNumber(gsvaResults$es.ob)])

# plot the correlation between ATF4 and EMT
plot(exprs(gsvaResults$es.ob)[1, 1:sampleNumber(gsvaResults$es.ob)], exprs(gsvaResults$es.ob)[2, 1:sampleNumber(gsvaResults$es.ob)], xlim=c(-1, 1), ylim=c(-1, 1), col=copdca_colors[gsvaResults$es.ob$indicator])
abline(lm(exprs(gsvaResults$es.ob)[1, 1:sampleNumber(gsvaResults$es.ob)] ~ exprs(gsvaResults$es.ob)[2, 1:sampleNumber(gsvaResults$es.ob)]), col="red")

# plot the ATF4 scores by COPD, Cancer groups
boxplot(exprs(gsvaResults$es.ob)[1, ] ~ gsvaResults$es.ob$indicator, col=copdca_colors, notch=TRUE, main="ATF4 GSVA Scores", names=c("Normal", "Cancer", "COPD", "COPD+Cancer"), ylab="GSVA Scores for ATF4")

# plot the EMT scores by COPD, Cancer groups
boxplot(exprs(gsvaResults$es.ob)[2, ] ~ gsvaResults$es.ob$indicator, col=copdca_colors, notch=TRUE, main="EMT GSVA Scores", names=c("Normal", "Cancer", "COPD", "COPD+Cancer"), ylab="GSVA Scores for EMT")

######### FORMER SMOKERS ONLY #############
# try the same test within former and current smokers separately
esetGSFormer <- removeFactorLevel(esetGS, "SMKc", "1")

gsvaResultsFormer <- gsva(esetGSFormer, genesets)

# Check for differences in atf4 and emt scores between COPD status groups
t.test(exprs(gsvaResultsFormer$es.ob)[1, gsvaResultsFormer$es.obs$COPD2_R7==0], exprs(gsvaResultsFormer$es.ob)[1, gsvaResultsFormer$es.obs$COPD2_R7==1])
t.test(exprs(gsvaResultsFormer$es.ob)[2, gsvaResultsFormer$es.obs$COPD2_R7==0], exprs(gsvaResultsFormer$es.ob)[2, gsvaResultsFormer$es.obs$COPD2_R7==1])

# Check for differences in atf4 and emt scores between Cancer status groups
t.test(exprs(gsvaResultsFormer$es.ob)[1, gsvaResultsFormer$es.obs$FinalCaDXc==0], exprs(gsvaResultsFormer$es.ob)[1, gsvaResultsFormer$es.obs$FinalCaDXc==1])
t.test(exprs(gsvaResultsFormer$es.ob)[2, gsvaResultsFormer$es.obs$FinalCaDXc==0], exprs(gsvaResultsFormer$es.ob)[2, gsvaResultsFormer$es.obs$FinalCaDXc==1])

# Check for differences in atf4 and emt scores between COPD+Cancer and COPD
t.test(exprs(gsvaResultsFormer$es.ob)[1, gsvaResultsFormer$es.obs$indicator==3], exprs(gsvaResultsFormer$es.ob)[1, gsvaResultsFormer$es.obs$indicator==4])
t.test(exprs(gsvaResultsFormer$es.ob)[2, gsvaResultsFormer$es.obs$indicator==3], exprs(gsvaResultsFormer$es.ob)[2, gsvaResultsFormer$es.obs$indicator==4])

cor.test(exprs(gsvaResultsFormer$es.ob)[1, 1:sampleNumber(gsvaResultsFormer$es.ob)], exprs(gsvaResultsFormer$es.ob)[2, 1:sampleNumber(gsvaResultsFormer$es.ob)])


######### CURRENT SMOKERS ONLY #############
# try the same test within former and current smokers separately
esetGSCurrent <- removeFactorLevel(esetGS, "SMKc", "2")

gsvaResultsCurrent <- gsva(esetGSCurrent, genesets)

# Check for differences in atf4 and emt scores between COPD status groups
t.test(exprs(gsvaResultsCurrent$es.ob)[1, gsvaResultsCurrent$es.obs$COPD2_R7==0], exprs(gsvaResultsCurrent$es.ob)[1, gsvaResultsCurrent$es.obs$COPD2_R7==1])
t.test(exprs(gsvaResultsCurrent$es.ob)[2, gsvaResultsCurrent$es.obs$COPD2_R7==0], exprs(gsvaResultsCurrent$es.ob)[2, gsvaResultsCurrent$es.obs$COPD2_R7==1])

# Check for differences in atf4 and emt scores between Cancer status groups
t.test(exprs(gsvaResultsCurrent$es.ob)[1, gsvaResultsCurrent$es.obs$FinalCaDXc==0], exprs(gsvaResultsCurrent$es.ob)[1, gsvaResultsCurrent$es.obs$FinalCaDXc==1])
t.test(exprs(gsvaResultsCurrent$es.ob)[2, gsvaResultsCurrent$es.obs$FinalCaDXc==0], exprs(gsvaResultsCurrent$es.ob)[2, gsvaResultsCurrent$es.obs$FinalCaDXc==1])

# Check for differences in atf4 and emt scores between COPD+Cancer and COPD
t.test(exprs(gsvaResultsCurrent$es.ob)[1, gsvaResultsCurrent$es.obs$indicator==3], exprs(gsvaResultsCurrent$es.ob)[1, gsvaResultsCurrent$es.obs$indicator==4])
t.test(exprs(gsvaResultsCurrent$es.ob)[2, gsvaResultsCurrent$es.obs$indicator==3], exprs(gsvaResultsCurrent$es.ob)[2, gsvaResultsCurrent$es.obs$indicator==4])

cor.test(exprs(gsvaResultsCurrent$es.ob)[1, 1:sampleNumber(gsvaResultsCurrent$es.ob)], exprs(gsvaResultsCurrent$es.ob)[2, 1:sampleNumber(gsvaResultsCurrent$es.ob)])


########## RELATIONSHIP OF ATF4, EMT, and SMOKING STATUS #############
# check for differences between current and former smokers with regards to atf4, emt
t.test(exprs(gsvaResults$es.ob)[1, gsvaResults$es.obs$SMKc==1], exprs(gsvaResults$es.ob)[1, gsvaResults$es.obs$SMKc==2])
t.test(exprs(gsvaResults$es.ob)[2, gsvaResults$es.obs$SMKc==1], exprs(gsvaResults$es.ob)[2, gsvaResults$es.obs$SMKc==2])

```


Try the above GSVA analysis of ATF4 and EMT in the super clean dataset
```{r atf4_emt_gsva_SuperClean}
genesets <- list(atf4=atf4Model$geneSymbols, emt=as.character(emt_genes$EMT_Genes))
forGenes <- lmFitWrapper(esetClean, c("RIN"),1, "fdr", 0.05, "For Genes")
esetGS <- esetSuperClean
gnsb <- forGenes$fit$genes$Symbol[which(!is.na(forGenes$fit$genes$Symbol))]
inds <- match(gnsb, forGenes$fit$genes$Symbol)

esetGS <- esetGS[inds, ]
rownames(esetGS) <- gnsb

require(GSVA)

# in place of genes this creates a row per gene set with a score per sample
gsvaResults <- gsva(esetGS, genesets)

# Check for differences in atf4 and emt scores between COPD status groups
t.test(exprs(gsvaResults$es.ob)[1, gsvaResults$es.obs$COPD2_R7==0], exprs(gsvaResults$es.ob)[1, gsvaResults$es.obs$COPD2_R7==1])
t.test(exprs(gsvaResults$es.ob)[2, gsvaResults$es.obs$COPD2_R7==0], exprs(gsvaResults$es.ob)[2, gsvaResults$es.obs$COPD2_R7==1])

# Check for differences in atf4 and emt scores between Cancer status groups
t.test(exprs(gsvaResults$es.ob)[1, gsvaResults$es.obs$FinalCaDXc==0], exprs(gsvaResults$es.ob)[1, gsvaResults$es.obs$FinalCaDXc==1])
t.test(exprs(gsvaResults$es.ob)[2, gsvaResults$es.obs$FinalCaDXc==0], exprs(gsvaResults$es.ob)[2, gsvaResults$es.obs$FinalCaDXc==1])

# Check for differences in atf4 and emt scores between COPD+Cancer and COPD
t.test(exprs(gsvaResults$es.ob)[1, gsvaResults$es.obs$indicator==3], exprs(gsvaResults$es.ob)[1, gsvaResults$es.obs$indicator==4])
t.test(exprs(gsvaResults$es.ob)[2, gsvaResults$es.obs$indicator==3], exprs(gsvaResults$es.ob)[2, gsvaResults$es.obs$indicator==4])

cor.test(exprs(gsvaResults$es.ob)[1, 1:sampleNumber(gsvaResults$es.ob)], exprs(gsvaResults$es.ob)[2, 1:sampleNumber(gsvaResults$es.ob)])

######### FORMER SMOKERS ONLY #############
# try the same test within former and current smokers separately
esetGSFormer <- removeFactorLevel(esetGS, "SMKc", "1")

gsvaResultsFormer <- gsva(esetGSFormer, genesets)

# Check for differences in atf4 and emt scores between COPD status groups
t.test(exprs(gsvaResultsFormer$es.ob)[1, gsvaResultsFormer$es.obs$COPD2_R7==0], exprs(gsvaResultsFormer$es.ob)[1, gsvaResultsFormer$es.obs$COPD2_R7==1])
t.test(exprs(gsvaResultsFormer$es.ob)[2, gsvaResultsFormer$es.obs$COPD2_R7==0], exprs(gsvaResultsFormer$es.ob)[2, gsvaResultsFormer$es.obs$COPD2_R7==1])

# Check for differences in atf4 and emt scores between Cancer status groups
t.test(exprs(gsvaResultsFormer$es.ob)[1, gsvaResultsFormer$es.obs$FinalCaDXc==0], exprs(gsvaResultsFormer$es.ob)[1, gsvaResultsFormer$es.obs$FinalCaDXc==1])
t.test(exprs(gsvaResultsFormer$es.ob)[2, gsvaResultsFormer$es.obs$FinalCaDXc==0], exprs(gsvaResultsFormer$es.ob)[2, gsvaResultsFormer$es.obs$FinalCaDXc==1])

# Check for differences in atf4 and emt scores between COPD+Cancer and COPD
t.test(exprs(gsvaResultsFormer$es.ob)[1, gsvaResultsFormer$es.obs$indicator==3], exprs(gsvaResultsFormer$es.ob)[1, gsvaResultsFormer$es.obs$indicator==4])
t.test(exprs(gsvaResultsFormer$es.ob)[2, gsvaResultsFormer$es.obs$indicator==3], exprs(gsvaResultsFormer$es.ob)[2, gsvaResultsFormer$es.obs$indicator==4])

cor.test(exprs(gsvaResultsFormer$es.ob)[1, 1:sampleNumber(gsvaResultsFormer$es.ob)], exprs(gsvaResultsFormer$es.ob)[2, 1:sampleNumber(gsvaResultsFormer$es.ob)])


######### CURRENT SMOKERS ONLY #############
# try the same test within former and current smokers separately
esetGSCurrent <- removeFactorLevel(esetGS, "SMKc", "2")

gsvaResultsCurrent <- gsva(esetGSCurrent, genesets)

# Check for differences in atf4 and emt scores between COPD status groups
t.test(exprs(gsvaResultsCurrent$es.ob)[1, gsvaResultsCurrent$es.obs$COPD2_R7==0], exprs(gsvaResultsCurrent$es.ob)[1, gsvaResultsCurrent$es.obs$COPD2_R7==1])
t.test(exprs(gsvaResultsCurrent$es.ob)[2, gsvaResultsCurrent$es.obs$COPD2_R7==0], exprs(gsvaResultsCurrent$es.ob)[2, gsvaResultsCurrent$es.obs$COPD2_R7==1])

# Check for differences in atf4 and emt scores between Cancer status groups
t.test(exprs(gsvaResultsCurrent$es.ob)[1, gsvaResultsCurrent$es.obs$FinalCaDXc==0], exprs(gsvaResultsCurrent$es.ob)[1, gsvaResultsCurrent$es.obs$FinalCaDXc==1])
t.test(exprs(gsvaResultsCurrent$es.ob)[2, gsvaResultsCurrent$es.obs$FinalCaDXc==0], exprs(gsvaResultsCurrent$es.ob)[2, gsvaResultsCurrent$es.obs$FinalCaDXc==1])

# Check for differences in atf4 and emt scores between COPD+Cancer and COPD
t.test(exprs(gsvaResultsCurrent$es.ob)[1, gsvaResultsCurrent$es.obs$indicator==3], exprs(gsvaResultsCurrent$es.ob)[1, gsvaResultsCurrent$es.obs$indicator==4])
t.test(exprs(gsvaResultsCurrent$es.ob)[2, gsvaResultsCurrent$es.obs$indicator==3], exprs(gsvaResultsCurrent$es.ob)[2, gsvaResultsCurrent$es.obs$indicator==4])

cor.test(exprs(gsvaResultsCurrent$es.ob)[1, 1:sampleNumber(gsvaResultsCurrent$es.ob)], exprs(gsvaResultsCurrent$es.ob)[2, 1:sampleNumber(gsvaResultsCurrent$es.ob)])


########## RELATIONSHIP OF ATF4, EMT, and SMOKING STATUS #############
# check for differences between current and former smokers with regards to atf4, emt
t.test(exprs(gsvaResults$es.ob)[1, gsvaResults$es.obs$SMKc==1], exprs(gsvaResults$es.ob)[1, gsvaResults$es.obs$SMKc==2])
t.test(exprs(gsvaResults$es.ob)[2, gsvaResults$es.obs$SMKc==1], exprs(gsvaResults$es.ob)[2, gsvaResults$es.obs$SMKc==2])

```
